name: Lint, Test & Deploy
on: [push, workflow_dispatch]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install dependencies
          run: npm ci
        - name: Run ESLint
          run: npm run lint
        - name: Run test
          run: npm test
        - name: Deploy
          run: echo "Deploying ..."